/**
 * WireGuard Permission Setup
 *
 * On macOS and Linux, wg-quick requires root (sudo) to create network interfaces.
 * This module detects whether passwordless sudo is already configured for the
 * specific binaries we use, and provides platform-appropriate guided setup.
 *
 * Flow:
 *   1. Check if sudoers entry already exists
 *   2. If not, attempt to create it (with user consent / OS-level auth prompt)
 *   3. On macOS, use osascript for a native password dialog
 *   4. On Linux, write a sudoers.d drop-in file
 *   5. On Windows, no action needed (WireGuard runs as SYSTEM service)
 */

import { execSync, exec } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { logger } from '../../utils/logger.js';

const SUDOERS_TAG = 'pc2-wireguard';
const SUDOERS_FILE = `/etc/sudoers.d/${SUDOERS_TAG}`;

export interface PermissionCheckResult {
  sudoConfigured: boolean;
  needsSetup: boolean;
  platform: string;
  message: string;
}

/**
 * Check whether the current user can run wg-quick via sudo without a password.
 */
export function checkWireGuardPermissions(wgQuickPath: string): PermissionCheckResult {
  const platform = process.platform;

  if (platform === 'win32') {
    return {
      sudoConfigured: true,
      needsSetup: false,
      platform: 'windows',
      message: 'Windows uses WireGuard tunnel service (no sudo needed)',
    };
  }

  if (existsSync(SUDOERS_FILE)) {
    try {
      const content = readFileSync(SUDOERS_FILE, 'utf-8');
      if (content.includes('wg-quick') || content.includes('wg quick')) {
        return {
          sudoConfigured: true,
          needsSetup: false,
          platform,
          message: 'Sudoers entry found for wg-quick',
        };
      }
    } catch {
      // Can't read sudoers file (expected for non-root)
    }
  }

  try {
    execSync(`sudo -n ${wgQuickPath} --version 2>/dev/null`, {
      stdio: 'pipe',
      timeout: 3000,
    });
    return {
      sudoConfigured: true,
      needsSetup: false,
      platform,
      message: 'sudo wg-quick works without password',
    };
  } catch {
    // sudo -n failed → password required
  }

  return {
    sudoConfigured: false,
    needsSetup: true,
    platform,
    message: `Passwordless sudo not configured for wg-quick at ${wgQuickPath}`,
  };
}

/**
 * Build the sudoers entry content for the current user and the given binary paths.
 */
function buildSudoersEntry(wgQuickPath: string, wgGoBinPath?: string): string {
  const user = process.env.USER || process.env.LOGNAME || 'nobody';
  const lines = [
    `# PC2 WireGuard — passwordless sudo for tunnel management`,
    `# Auto-generated by PC2 Node. Remove this file to revoke.`,
    `${user} ALL=(root) NOPASSWD: ${wgQuickPath} up *`,
    `${user} ALL=(root) NOPASSWD: ${wgQuickPath} down *`,
  ];
  if (wgGoBinPath) {
    lines.push(`${user} ALL=(root) NOPASSWD:SETENV: /usr/bin/env WG_QUICK_USERSPACE_IMPLEMENTATION=${wgGoBinPath} ${wgQuickPath} up *`);
    lines.push(`${user} ALL=(root) NOPASSWD:SETENV: /usr/bin/env WG_QUICK_USERSPACE_IMPLEMENTATION=${wgGoBinPath} ${wgQuickPath} down *`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Attempt to install the sudoers entry. Returns true on success.
 *
 * macOS: Uses osascript to show a native authorization dialog.
 * Linux: Writes via sudo tee (may prompt in terminal or fail silently in GUI).
 */
export async function setupWireGuardSudoers(
  wgQuickPath: string,
  wgGoBinPath?: string,
): Promise<{ success: boolean; message: string }> {
  const platform = process.platform;

  if (platform === 'win32') {
    return { success: true, message: 'No sudo needed on Windows' };
  }

  const entry = buildSudoersEntry(wgQuickPath, wgGoBinPath);
  logger.info(`[WireGuard:sudoers] Attempting to install sudoers entry for wg-quick`);

  if (platform === 'darwin') {
    return setupMacOS(entry);
  }
  return setupLinux(entry);
}

async function setupMacOS(entry: string): Promise<{ success: boolean; message: string }> {
  const escaped = entry.replace(/"/g, '\\"').replace(/\n/g, '\\n');
  const script = `
    do shell script "echo \\"${escaped}\\" > ${SUDOERS_FILE} && chmod 0440 ${SUDOERS_FILE}" with administrator privileges
  `.trim();

  return new Promise((resolve) => {
    exec(`osascript -e '${script}'`, { timeout: 60_000 }, (error) => {
      if (error) {
        logger.warn(`[WireGuard:sudoers] macOS setup cancelled or failed: ${error.message}`);
        resolve({
          success: false,
          message: 'Permission setup cancelled. You can set it up manually by running:\n' +
            `  sudo tee ${SUDOERS_FILE} << 'EOF'\n${entry}EOF\n  sudo chmod 0440 ${SUDOERS_FILE}`,
        });
        return;
      }
      logger.info('[WireGuard:sudoers] macOS sudoers entry installed');
      resolve({ success: true, message: 'Sudoers entry installed successfully' });
    });
  });
}

async function setupLinux(entry: string): Promise<{ success: boolean; message: string }> {
  const escapedEntry = entry.replace(/'/g, "'\\''");
  const cmd = `echo '${escapedEntry}' | sudo tee ${SUDOERS_FILE} > /dev/null && sudo chmod 0440 ${SUDOERS_FILE}`;

  return new Promise((resolve) => {
    exec(cmd, { timeout: 30_000 }, (error) => {
      if (error) {
        logger.warn(`[WireGuard:sudoers] Linux setup failed: ${error.message}`);
        resolve({
          success: false,
          message: 'Automated setup failed. Run the following manually:\n' +
            `  sudo tee ${SUDOERS_FILE} << 'EOF'\n${entry}EOF\n  sudo chmod 0440 ${SUDOERS_FILE}`,
        });
        return;
      }
      logger.info('[WireGuard:sudoers] Linux sudoers entry installed');
      resolve({ success: true, message: 'Sudoers entry installed successfully' });
    });
  });
}

/**
 * Generate manual setup instructions for the user.
 */
export function getManualSetupInstructions(wgQuickPath: string, wgGoBinPath?: string): string {
  const entry = buildSudoersEntry(wgQuickPath, wgGoBinPath);
  const platform = process.platform;

  if (platform === 'win32') {
    return 'Windows: Install WireGuard from https://www.wireguard.com/install/ — no additional setup needed.';
  }

  return [
    'To enable WireGuard tunnel management, run the following in your terminal:',
    '',
    `  sudo tee ${SUDOERS_FILE} << 'EOF'`,
    entry.trimEnd(),
    'EOF',
    `  sudo chmod 0440 ${SUDOERS_FILE}`,
    '',
    'To remove later:',
    `  sudo rm ${SUDOERS_FILE}`,
  ].join('\n');
}
