/**
 * @elacity-js/access — AES-GCM encryption (creator side)
 *
 * Encrypts arbitrary data using AES-256-GCM via WebCrypto API.
 * Used by the Creator Dashboard to encrypt assets before IPFS upload.
 *
 * The encryption key is generated by Lit Protocol and gated by
 * access control conditions (ACCESS_TOKEN ownership).
 *
 * No WASM, no SharedArrayBuffer — runs in any browser or Node.js context.
 */

import { buildAccessTokenCondition } from '../lit/conditions.js';
import { AES_IV_LENGTH } from '../constants.js';
import { getCryptoApi, base64ToUint8Array } from '../utils.js';
import type { LitSession } from '../lit/session.js';
import type { EncryptParams, EncryptResult } from '../types.js';

/**
 * Encrypt data using Lit Protocol access conditions.
 *
 * Flow:
 * 1. Build access conditions (ERC-1155 balanceOf check for ACCESS_TOKEN)
 * 2. Call Lit's encrypt() which:
 *    a. Generates a random symmetric key
 *    b. Encrypts the data with that key (AES-GCM)
 *    c. Splits the key into shares across Lit nodes
 *    d. Associates shares with the access conditions
 * 3. Returns encrypted data + metadata needed for decryption
 *
 * The encrypted data and dataToEncryptHash must be stored in the
 * asset's metadata on IPFS so consumers can decrypt later.
 */
export async function encryptBuffer(
  session: LitSession,
  data: Uint8Array,
  params: EncryptParams
): Promise<EncryptResult> {
  const { ledger, tokenId } = params;
  const client = session.getClient();

  const conditions = buildAccessTokenCondition(ledger, tokenId);

  // EncryptSdkParams = { dataToEncrypt, unifiedAccessControlConditions }
  const encryptResult = await client.encrypt({
    dataToEncrypt: data,
    unifiedAccessControlConditions: conditions as unknown[],
  });

  const keyId = `${ledger}:${tokenId}`;

  return {
    encrypted: base64ToUint8Array(encryptResult.ciphertext),
    conditions,
    keyId,
    algorithm: 'aes-gcm',
    dataToEncryptHash: encryptResult.dataToEncryptHash ?? '',
  };
}

/**
 * Encrypt raw data locally using WebCrypto AES-256-GCM.
 * For cases where the symmetric key is managed externally
 * (not via Lit Protocol's built-in encrypt).
 */
export async function encryptWithKey(
  data: Uint8Array,
  keyBytes: Uint8Array
): Promise<{ encrypted: Uint8Array; iv: Uint8Array }> {
  const cryptoApi = getCryptoApi();
  const iv = cryptoApi.getRandomValues(new Uint8Array(AES_IV_LENGTH));

  const key = await cryptoApi.subtle.importKey(
    'raw',
    keyBytes.buffer as ArrayBuffer,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt']
  );

  const encrypted = await cryptoApi.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    data.buffer as ArrayBuffer
  );

  return {
    encrypted: new Uint8Array(encrypted),
    iv,
  };
}

