#!/bin/bash
#
# PC2 — one-line installer.
#
# Pulls the prebuilt image (PC2 + Elastos Node Manager extension bundled)
# from GitHub Container Registry, writes a docker-compose.yml, brings the
# stack up. Survives reboots via Docker's `--restart unless-stopped`. Safe
# to re-run — pulls the latest image and reconciles the container.
#
# Naming convention: this is "PC2" to the operator. The Elastos Node Manager
# extension is bundled inside but is not a separate product — it's intended
# to land upstream as a normal extension. Internal codename is ENM; we keep
# that out of operator-facing strings on purpose.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/4HM3DMD/pc2-testing/main/scripts/install.sh | bash
#
# Or with custom port / dir / name:
#   curl -sSL ... | bash -s -- --port 8080 --dir /opt/pc2 --name "Berlin BPoS"
#
# Tested on Ubuntu 22.04 / 24.04, Debian 12. macOS works too if Docker
# Desktop is already installed (we won't install Docker for you on macOS).
#
# Note: there's also `scripts/install-pc2.sh` in this repo — that's the
# upstream Elacity script which pulls the *vanilla* PC2 image without our
# extension bundle. Use this script (`install.sh`) instead.

set -euo pipefail

# ---------- Defaults & flags ------------------------------------------------

PC2_DIR="${PC2_DIR:-$HOME/pc2}"
PC2_PORT="${PC2_PORT:-4100}"
PC2_WS_PORT="${PC2_WS_PORT:-4200}"
PC2_NODE_NAME="${PC2_NODE_NAME:-My PC2 Node}"
# Image is auto-derived from this repo's slug. Override with --image to pin
# a sha or use a fork.
IMAGE="${PC2_IMAGE:-ghcr.io/4hm3dmd/pc2-testing:latest}"
EXPOSE_BPOS="${EXPOSE_BPOS:-1}"   # 1 = expose 20338+20339 publicly (BPoS); 0 = loopback only

while [[ $# -gt 0 ]]; do
    case $1 in
        --port)         PC2_PORT="$2"; shift 2 ;;
        --ws-port)      PC2_WS_PORT="$2"; shift 2 ;;
        --dir)          PC2_DIR="$2"; shift 2 ;;
        --name)         PC2_NODE_NAME="$2"; shift 2 ;;
        --image)        IMAGE="$2"; shift 2 ;;
        --no-bpos)      EXPOSE_BPOS=0; shift ;;
        --help|-h)
            cat <<EOF
PC2 installer

Options:
  --port N         PC2 web port  (default: 4100)
  --ws-port N      PC2 WebSocket port (default: 4200)
  --dir PATH       Install directory (default: \$HOME/pc2)
  --name "X"       Node name shown in the launcher (default: "My PC2 Node")
  --image NAME     Override image (default: ghcr.io/4hm3dmd/pc2-testing:latest)
  --no-bpos        Bind ela P2P/DPoS ports to loopback only (full-node mode).
                   Default exposes 20338 + 20339 publicly for BPoS supernodes.
EOF
            exit 0
            ;;
        *)              echo "Unknown flag: $1" >&2; exit 1 ;;
    esac
done

# ---------- ANSI ------------------------------------------------------------

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

say()  { printf "${CYAN}==> %s${NC}\n" "$*"; }
ok()   { printf "${GREEN}✓ %s${NC}\n" "$*"; }
warn() { printf "${YELLOW}! %s${NC}\n" "$*"; }
die()  { printf "${RED}✗ %s${NC}\n" "$*" >&2; exit 1; }

# ---------- Prerequisites ---------------------------------------------------

if [[ "$(uname -s)" != "Linux" && "$(uname -s)" != "Darwin" ]]; then
    die "Unsupported OS: $(uname -s). PC2 installer supports Linux + macOS."
fi

if ! command -v docker >/dev/null 2>&1; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
        die "Docker Desktop not found. Install it from https://docker.com/products/docker-desktop and re-run."
    fi
    say "Docker not found — installing via get.docker.com..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER" 2>/dev/null || true
    ok "Docker installed (you may need to log out + back in for non-root usage)"
fi

if ! docker compose version >/dev/null 2>&1; then
    say "Docker Compose plugin missing — installing..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq docker-compose-plugin
    ok "Docker Compose plugin installed"
fi

# ---------- Lay out the install dir -----------------------------------------

mkdir -p "$PC2_DIR/data"
cd "$PC2_DIR"

# Decide port-binding strategy. BPoS supernodes need 20338 + 20339 publicly
# reachable so peers can dial in. Full-node operators don't (they can stay
# fully outbound). Toggle with --no-bpos.
if [[ "$EXPOSE_BPOS" == "1" ]]; then
    BPOS_PORTS=$'      - "20338:20338"\n      - "20339:20339"'
else
    BPOS_PORTS=$'      - "127.0.0.1:20338:20338"\n      - "127.0.0.1:20339:20339"'
fi

cat > docker-compose.yml <<COMPOSE
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit freely — re-running the installer will not overwrite this file unless
# you delete it first.
services:
  pc2:
    image: ${IMAGE}
    container_name: pc2
    restart: unless-stopped
    ports:
      - "${PC2_PORT}:4100"
      - "${PC2_WS_PORT}:4200"
      # ela JSON-RPC stays on loopback by default — operator widens via the
      # PC2 dashboard's Settings → Mainchain Advanced → WhiteIPList.
      - "127.0.0.1:20336:20336"
${BPOS_PORTS}
      # ela read-only ports — loopback only.
      - "127.0.0.1:20333:20333"
      - "127.0.0.1:20334:20334"
      - "127.0.0.1:20335:20335"
    volumes:
      - ./data:/data
    environment:
      - PC2_NODE_NAME=${PC2_NODE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4100/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
COMPOSE

ok "docker-compose.yml written to $PC2_DIR"

# ---------- Pull image and start --------------------------------------------

say "Pulling ${IMAGE} (first run downloads ~1.6 GB)..."
docker compose pull
ok "Image pulled"

say "Starting PC2..."
docker compose up -d
ok "Container started"

# ---------- Result ----------------------------------------------------------

# Try to get the host's primary IPv4 — for the URL we print.
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
[[ -z "$HOST_IP" ]] && HOST_IP="$(ipconfig getifaddr en0 2>/dev/null)"
[[ -z "$HOST_IP" ]] && HOST_IP="<server-ip>"

cat <<EOF

${GREEN}╔══════════════════════════════════════════════════════════════════╗
║                          PC2 installed                            ║
╚══════════════════════════════════════════════════════════════════╝${NC}

  Dashboard:   http://${HOST_IP}:${PC2_PORT}
  Logs:        cd $PC2_DIR && docker compose logs -f
  Stop:        cd $PC2_DIR && docker compose down
  Update:      cd $PC2_DIR && docker compose pull && docker compose up -d
  Persistent:  $PC2_DIR/data  (everything PC2 stores lives here)

Next steps:
  1. Open the dashboard in your browser.
  2. Claim ownership with your wallet.
  3. Click the Elastos Node Manager icon in the launcher.
  4. Hit "Install ela for me" — wait ~5 min for the build.
  5. Walk the rest of the wizard.

EOF
